name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  contents: read

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '17', '21' ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v3

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ matrix.java }}

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build and test
        run: ./gradlew --no-daemon clean build --stacktrace

      - name: Upload test reports
        if: success() || failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports-java-${{ matrix.java }}
          path: |
            **/build/reports/tests/test/**
            **/build/test-results/test/**
          if-no-files-found: ignore
          retention-days: 7

      - name: Upload JAR artifact (only Java 21, push)
        if: github.event_name == 'push' && matrix.java == '21'
        uses: actions/upload-artifact@v4
        with:
          name: libs
          path: |
            **/build/libs/*.jar
          if-no-files-found: warn
          retention-days: 7
---
# file: .github/workflows/release.yml
name: Release

on:
  push:
    tags:
      - v*

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build (with tests)
        run: ./gradlew --no-daemon clean build --stacktrace

      - name: Create GitHub Release and upload JARs
        uses: softprops/action-gh-release@v2
        with:
          files: |
            **/build/libs/*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}